### ISSUE TITLE
action detection program mentioned in the paper

### ISSUE THREAD

**Issue by xmba15** [miquelmarti/Okutama-Action#1]
Can you please release the program for action detection that is mentioned in your paper?

**Comment by miquelmarti** [comment]
Please contact @Mohammadamin-Barekatain for anything related to the paper. He will be happy to help.

**Comment by Mohammadamin-Barekatain** [comment]
@bajsk you can find the code here: https://github.com/Mohammadamin-Barekatain/caffe
Since this code was not intended for public release, you may have some difficulties in running the scripts for training or visualization of the results.
If you only want the final trained model, please contact me via Email.
