### ISSUE TITLE
poor annotation quality

### ISSUE THREAD

**Issue by liudakai2** [miquelmarti/Okutama-Action#6]
There are some annotations, taking bounding boxes as an instance, that are pretty precise in some videos like 1.1.2, 1.2.1, 2.1.2, 2.2.2, et al. While there still remains a large number of poorly annotated bounding boxes in other videos. Taking 2.1.1 for an example, during this video the 20th frame is well annotated, but the 140th, 350th frame and so many other frames are ridiculously wrong. Is there anything wrong with the annotation files that I have downloaded from http://okutama-action.org/ ? Could you please tell me how to correct these wrong annotations?

20th frame
![2 1 1-20](https://user-images.githubusercontent.com/50127983/105132236-86e4ef00-5b25-11eb-937c-e11d3a461701.jpg)

140th frame
![2 1 1-140](https://user-images.githubusercontent.com/50127983/105132256-9106ed80-5b25-11eb-88c1-42f701af0813.jpg)

350th frame
![2 1 1-350](https://user-images.githubusercontent.com/50127983/105132265-9b28ec00-5b25-11eb-9254-f7d48fa3a2ce.jpg)

**Comment by miquelmarti** [comment]
Hi Liu. Annotations were interpolated between frames so in cases where there are abrupt camera changes while interpolating the annotation is indeed quite off. We wanted to fix that but we never had the time so sorry about this but we cannot help you with it at this time. If you need this fixes to the annotations and do them yourself we would be happy to update them here.
It could also be related to problems with extracting frames from the video files. Later versions of ffmpeg gave different frame rates than the ones that were used to annotate the video even when using the default frame rate at which the video was supposedly taken, resulting in mismatch between number of frames extracted and the frames expected from the annotations and thus between the annotations and contents in the video if you use them anyway... However I suspect that is not the case for you because you would have seen it.
